### ISSUE TITLE
w0wzCDM and redshift squared models

### ISSUE THREAD

**Issue by Rockdeldiablo** [ja-vazquez/SimpleMC#21]
Hello Dr. Vazquez,
i am an undergraduate student who has been tasked to replicate some results from a paper where the authors use an mcmc software to find the best fit parameter values for different cosmological models (lcdm, w0wacdm,w0wzcdm, and the redshift squared case).
The first two are among the models already available, but the the last 2 are not. i was trying to set up a new model derived from the standard lcdm for the w0wzcdm case (w(z) = w_0+w_az)  but i am stuck at the part where i need to modify the equation. should i  add  extra parameters w0,w_a  like
`w0 = Parameter('w0', 0.1, 0.001, (0, 0.2), '\w_0')` 
`wa = Parameter('wa', 0.1, 0.001, (0, 0.2), '\w_a')` 

`cosmo_model = 'Ocb/a**3+Omrad/a**4+(1-Ocb - Omrad )* e**(-3*wa*(1/a-1) ) /a**3(1+w0+wa)      `

or there are a built-in parameters for w0,w_a ?  

sorry if this is a stupid question, i am fairly new to the field

also, how do i explore the algebraic form of the other models implemented?

**Comment by igomezv** [comment]
There are built-in parameters for w0 and wa in the `simplemc.cosmo.paramDefs` module. 

Also, you can define new paremeters externally. An example of this is [here](https://igomezv.github.io/SimpleMC/tuto_simple_model.html ).
