### ISSUE TITLE
Understanding Matter Density Parameter

### ISSUE THREAD

**Issue by seVenVo1d** [ja-vazquez/SimpleMC#43]
Hello,  @ja-vazquez and @igomezv

I am a M.Sc. Physics Student at Istanbul Technical University. I am trying to create a new model and in this model I have to define matter density. However, it seems there are two matter density definitions. The first one seems to be `Om` and the second is `Ocb`.

In  **SimpleMC**, the only definition I could have find for `Om` is in `simplemc/models/LCDMCosmology.py`, and it is written as

    # this returns the Wang+Wang variables in a vec
    def WangWangVec(self):
        Omh2   = self.Ocb*self.h**2+self.Omnuh2
        ...

Meanwhile, for `Ocb` there is

    self.Ocb = self.Om-self.Omnu-self.Omrad

again at the same file.

But these two definitions are also seems strange and contradictory... Also, In general the `RHSquared_a()` function defined as

    (self.Ocb/a**3+self.Ok/a**2+self.Omrad/a**4+NuContrib+(1.0-self.Om-self.Ok))

So first `Ocb` is used as a normal matter density,  but later while writing the DE energy density, `Om` is used...which is confusing..

My questions:

1) What are the definitions (mathematically) of `Om` and `Ocb`
2) How should I write the matter density, if I want to create a new model ? Should I define a new matter density term by using `Ocb` and `Om` ?

Thanks,
Arman

**Comment by seVenVo1d** [comment]
Does `Ocb` represents

$$
\Omega_{\rm cb} = \Omega_{\rm CDM} + \Omega{\rm baryon}
$$

**Comment by igomezv** [comment]
Hi Arman, 

They are different parameters. $\Omega_{cb}$ represents baryons plus cold dark matter, $\Omega_b$ is only baryonic matter and $\Omega_m$ contains all the matter content (including radiation and neutrinos).

As for your second question, you need to use $\Omega_{cb}$ as matter density for your new model in the Friedmann equation, e. g. `E(z) = self.Ocb/a**3+self.Omrad/a**4+NuContrib+(1 -self. Om)`. And you can use the total matter density $\Omega_m$ for the cosmological constant represented through `(1 - self.Om)`.

I hope you find this answer helpful.

Best regards,
Isidro

**Comment by igomezv** [comment]
> Does `Ocb` represents
> 
> Ωcb=ΩCDM+Ωbaryon

That's right.

**Comment by igomezv** [comment]
> But I understand the idea now. Also, `self.Omrad` is the only the radiation contribution right ?
Yes, it is right.

**Comment by seVenVo1d** [comment]
Okay, thanks a lot. I really appreciate it.
